### ISSUE TITLE
support for sitemap index ? 

### ISSUE THREAD

**Issue by jdkealy** [hashobject/sitemap#3]
Is there are way to generate a sitemap index using this lib ?

**Comment by podviaznikov** [comment]
@jdkealy what do you mean by that? This library generates sitemap file, what do you mean by index?

**Comment by jdkealy** [comment]
Like this: 
https://support.google.com/webmasters/answer/75712?hl=en

some content websites are too big for one sitemap... you divide the sitemap into multiple sitemaps and gzip them

**Comment by podviaznikov** [comment]
It doesn't have that. I wasn't aware of this feature. If you want to submit PR I would happily merge it.
