### ISSUE TITLE
Publish version 0.3.0 to Clojars

### ISSUE THREAD

**Issue by martinklepsch** [hashobject/sitemap#5]
Hey Anton, hope you're doing well :wave: 

Would you mind publishing version 0.3.0 to Clojars? 

We'd love to use some of the new stuff for cljdoc's sitemap stuff (https://github.com/cljdoc/cljdoc/pull/191) 

Thanks a bunch!

**Comment by podviaznikov** [comment]
ah sorry. Will try to do that!

**Comment by martinklepsch** [comment]
Thanks! `[sitemap "0.3.0"]` is now available.
